#!/usr/bin/env bash
# Generate backend/.env from the NUCLEUS vault in HEAL Engineering 1Password.
#
# Mirrors the HEAL fastapi-1password-template convention: every item in the
# vault becomes one env var. The item *title* is the env var name (e.g.
# DB_PASSWORD, ANTHROPIC_API_KEY, DB_HOST). The item's `password` field holds
# the value.
#
# Add a new env var:
#   1. Create an item in the NUCLEUS vault titled exactly the env var name
#      (uppercase, underscores, e.g. ANTHROPIC_API_KEY).
#   2. Put the value in the `password` field.
#   3. Re-run `task env:generate`.

set -euo pipefail

VAULT="NUCLEUS"
OUTPUT_FILE="backend/.env"

if ! op vault get "$VAULT" >/dev/null 2>&1; then
  echo "ERROR: 1Password vault '$VAULT' not found." >&2
  echo "Create it in the HEAL Engineering 1Password org and add items there." >&2
  exit 1
fi

cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/generate-env.sh from 1Password vault: $VAULT
# DO NOT COMMIT — regenerate with: task env:generate
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

EOF

count=0
while IFS= read -r title; do
  value=$(op read "op://${VAULT}/${title}/password" 2>/dev/null || true)
  if [ -n "$value" ]; then
    echo "${title}=${value}" >> "$OUTPUT_FILE"
    count=$((count + 1))
  fi
done < <(op item list --vault="$VAULT" --format json | jq -r '.[].title')

echo "Wrote $count entries to $OUTPUT_FILE from vault $VAULT"
