#!/usr/bin/env bash
# Generate ./.env (repo root) from the NUCLEUS vault in HEAL Engineering 1Password.
#
# Single shared env file for backend + autopilot — both Python services read
# it. (The recruiter UI is Vite and uses its own VITE_* env if needed; it does
# not consume secrets from 1Password.)
#
# Mirrors the HEAL fastapi-1password-template convention: every item in the
# vault becomes one env var. The item *title* is the env var name (e.g.
# DB_PASSWORD, ANTHROPIC_API_KEY). The item's `password` field holds the value.
#
# Add a new env var:
#   1. Create an item in the NUCLEUS vault titled exactly the env var name
#      (uppercase, underscores, e.g. ANTHROPIC_API_KEY).
#   2. Put the value in the `password` field.
#   3. Re-run `task env:generate`.

set -euo pipefail

VAULT="NUCLEUS"
OUTPUT_FILE=".env"

# Local dev frontend ports the autopilot UI is allowed to come from. We always
# union these with whatever CORS_ALLOW_ORIGINS lives in 1Password so the UI
# never breaks just because the vault's value drifted.
LOCAL_FRONTEND_ORIGINS="http://localhost:5173,http://localhost:5174,http://localhost:5175"

if ! op vault get "$VAULT" >/dev/null 2>&1; then
  echo "ERROR: 1Password vault '$VAULT' not found." >&2
  echo "Create it in the HEAL Engineering 1Password org and add items there." >&2
  exit 1
fi

cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/generate-env.sh from 1Password vault: $VAULT
# Shared by backend + autopilot. DO NOT COMMIT — regenerate with: task env:generate
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

EOF

count=0
cors_seen=0
while IFS= read -r title; do
  value=$(op read "op://${VAULT}/${title}/password" 2>/dev/null || true)
  if [ -n "$value" ]; then
    if [ "$title" = "CORS_ALLOW_ORIGINS" ]; then
      # Ensure local frontend dev ports are always allowed regardless of vault drift.
      merged="${value},${LOCAL_FRONTEND_ORIGINS}"
      # Dedup origins while preserving order.
      merged=$(printf '%s' "$merged" | awk -v RS=, -v ORS=, '!seen[$0]++' | sed 's/,$//')
      echo "${title}=${merged}" >> "$OUTPUT_FILE"
      cors_seen=1
    else
      echo "${title}=${value}" >> "$OUTPUT_FILE"
    fi
    count=$((count + 1))
  fi
done < <(op item list --vault="$VAULT" --format json | jq -r '.[].title')

# If the vault didn't have a CORS_ALLOW_ORIGINS item at all, write the local
# default so the autopilot UI can connect.
if [ "$cors_seen" = "0" ]; then
  echo "CORS_ALLOW_ORIGINS=${LOCAL_FRONTEND_ORIGINS}" >> "$OUTPUT_FILE"
  count=$((count + 1))
fi

echo "Wrote $count entries to $OUTPUT_FILE from vault $VAULT"
